name: "churn_dbt"
version: "1.0.0"
config-version: 2

profile: "churn_profile"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  churn_dbt:
    stg:
      +schema: stg
      +materialized: table
    marts:
      +schema: analytics
      +materialized: table
