churn_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'postgres') }}"
      user: "{{ env_var('POSTGRES_USER', 'hg_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'hg_password') }}"
      dbname: "{{ env_var('POSTGRES_DATA_WAREHOUSE', 'hg_dw') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      schema: public
      threads: 4
